# 🧠 Reward Modeling with TRL (GPT2 Example)

Converted from the original Hugging Face script for Jupyter Notebook use.

In [ ]:
# Copyright 2020-2025 The HuggingFace Team. All rights reserved.
# Licensed under the Apache License, Version 2.0 (the "License").
#     http://www.apache.org/licenses/LICENSE-2.0

### 🧩 1. Install dependencies

In [1]:
!pip install -q trl trackio kernels accelerate datasets transformers

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 528.8/528.8 kB 16.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 53.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.1/55.1 kB 6.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.2/24.2 MB 108.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 6.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 150.2 MB/s eta 0:00:00

###📚2. Initialize

In [2]:
model_name = 'gpt2'
# path where reward model should be saved
output_dir = ''
data_dir = ''

In [3]:
from google.colab import drive
drive.mount('/content/drive')

from google.colab import userdata
userdata.get('HF_TOKEN')
from huggingface_hub import notebook_login
notebook_login()

output_dir = '/content/drive/Othercomputers/My Mac/Google Drive/Colab Notebooks/Reinforcement-learning/outputs/Gpt2-Reward'
data_dir = '/content/drive/Othercomputers/My Mac/Google Drive/Colab Notebooks/Reinforcement-learning/outputs/hh-rlhf'

Mounted at /content/drive

### ⚙️ 2. Imports and logging setup

In [4]:
import os
import torch
from accelerate import logging
from datasets import load_dataset
from transformers import AutoModelForSequenceClassification, HfArgumentParser

from trl import (
    ModelConfig,
    RewardConfig,
    RewardTrainer,
    ScriptArguments,
    get_kbit_device_map,
    get_peft_config,
    get_quantization_config,
)

logger = logging.get_logger(__name__)
os.environ.setdefault("TRACKIO_SPACE_ID", "trl-trackio")

'trl-trackio'

### 📦 3. Define helper configs for notebook runs

In [6]:
from dataclasses import dataclass

script_args = ScriptArguments(
    dataset_name="Anthropic/hh-rlhf"
)
training_args = RewardConfig(
    output_dir=output_dir,
    per_device_train_batch_size=5, # 10hrs for 10, 12 for 30+, 11.5 for 20, 8hrs for 5 on L4 GPU
    num_train_epochs=3,
    gradient_checkpointing=True,
    learning_rate=1e-5,
    eval_strategy="steps",
    save_total_limit=1,           # keeps only the best and the last checkpoint
    load_best_model_at_end=True,  # reloads the best model at the end of training
    metric_for_best_model="eval_loss", # monitor validation loss
    greater_is_better=False,      # lower loss is better
    eval_steps=10000,
    save_steps=10000,
    max_length=1024,
)
# training_args = TrainingArguments(
#     output_dir="./reward_model_checkpoints",
#     evaluation_strategy="epoch",  # or "steps"
#     save_strategy="epoch",        # must match evaluation_strategy
#     save_total_limit=1,           # keeps only the best and the last checkpoint
#     load_best_model_at_end=True,  # reloads the best model at the end of training
#     metric_for_best_model="eval_loss", # monitor validation loss
#     greater_is_better=False,      # lower loss is better
#     # other standard training args like learning_rate, batch_size, etc.
# )

model_args = ModelConfig(
    model_name_or_path="gpt2",
    # trust_remote_code=True,
)
training_args.gradient_checkpointing_kwargs = dict(use_reentrant=False)

### 🧠 4. Load model and tokenizer

In [7]:
dtype = model_args.dtype if model_args.dtype in ["auto", None] else getattr(torch, model_args.dtype)
model_kwargs = dict(
    revision=model_args.model_revision,
    use_cache=False if training_args.gradient_checkpointing else True,
    dtype=dtype,
)

quantization_config = get_quantization_config(model_args)
if quantization_config is not None:
    model_kwargs["device_map"] = get_kbit_device_map()
    model_kwargs["quantization_config"] = quantization_config

model = AutoModelForSequenceClassification.from_pretrained(
    model_args.model_name_or_path,
    num_labels=1,
    trust_remote_code=model_args.trust_remote_code,
    **model_kwargs,
)

if model_args.use_peft and model_args.lora_task_type != "SEQ_CLS":
    logger.warning(
        "⚠️ PEFT `task_type` differs from SEQ_CLS — this can cause silent bugs."
    )

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2ForSequenceClassification LOAD REPORT from: gpt2
Key                  | Status     |
---------------------+------------+-
h.{0...11}.attn.bias | UNEXPECTED |
score.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

### 📚 5. Load dataset

In [8]:
dataset = load_dataset(data_dir, split="train")
eval_dataset = load_dataset(data_dir, split="test")
print(dataset)

Generating train split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

Dataset({
    features: ['chosen', 'rejected'],
    num_rows: 160800
})

### 🚀 6. Train Reward Model

In [9]:
trainer = RewardTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset,
    eval_dataset=eval_dataset,
    peft_config=get_peft_config(model_args),
)

trainer.train()

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Adding EOS to train dataset:   0%|          | 0/160800 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/160800 [00:00<?, ? examples/s]

Token indices sequence length is longer than the specified maximum sequence length for this model (1028 > 1024). Running this sequence through the model will result in indexing errors

Filtering train >1024 tokens:   0%|          | 0/160800 [00:00<?, ? examples/s]

Adding EOS to eval dataset:   0%|          | 0/8552 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/8552 [00:00<?, ? examples/s]

Filtering eval >1024 tokens:   0%|          | 0/8552 [00:00<?, ? examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

KeyboardInterrupt:

### 📊 7. Evaluate and save model

In [10]:
trainer.save_model(training_args.output_dir)

if training_args.eval_strategy != "no":
    metrics = trainer.evaluate()
    trainer.log_metrics("eval", metrics)
    trainer.save_metrics("eval", metrics)

if training_args.push_to_hub:
    trainer.push_to_hub(dataset_name=script_args.dataset_name)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

***** eval metrics *****
  eval_loss = 0.6376

### ✅ 8. Quick inference sanity check

In [19]:
from transformers import AutoTokenizer

# tokenizer = AutoTokenizer.from_pretrained(model_args.model_name_or_path)
prompt = "The assistant is not polite and helpful."
response = "yes"
inputs = tokenizer(prompt+response, return_tensors="pt").to(model.device)

with torch.no_grad():
    reward = model(**inputs).logits.item()

print(f"Reward score: {reward:.4f}")

Reward score: 0.6120

In [5]:
!pip install -q rewardbench

  Preparing metadata (setup.py) ... done
  Building wheel for wavedrom (setup.py) ... done

In [5]:
from datasets import load_dataset
import tqdm

dataset = load_dataset("allenai/reward-bench", split="filtered")
print(f"Total examples: {len(dataset)}")
print(f"\nUnique subset values:")
print(dataset.unique("subset"))
print(f"\nSubset distribution:")
print(dataset.to_pandas()["subset"].value_counts())

README.md: 0.00B [00:00, ?B/s]

data/raw-00000-of-00001.parquet:   0%|          | 0.00/5.59M [00:00<?, ?B/s]

data/filtered-00000-of-00001.parquet:   0%|          | 0.00/2.35M [00:00<?, ?B/s]

Generating raw split:   0%|          | 0/5123 [00:00<?, ? examples/s]

Generating filtered split:   0%|          | 0/2985 [00:00<?, ? examples/s]

Total examples: 2985

Unique subset values:
['alpacaeval-easy', 'alpacaeval-hard', 'alpacaeval-length', 'mt-bench-easy', 'mt-bench-med', 'mt-bench-hard', 'llmbar-natural', 'llmbar-adver-neighbor', 'llmbar-adver-GPTInst', 'llmbar-adver-GPTOut', 'llmbar-adver-manual', 'refusals-dangerous', 'refusals-offensive', 'xstest-should-respond', 'xstest-should-refuse', 'donotanswer', 'hep-python', 'hep-go', 'hep-cpp', 'hep-js', 'hep-rust', 'hep-java', 'math-prm']

Subset distribution:
subset
math-prm                 447
xstest-should-respond    250
hep-python               164
hep-java                 164
hep-js                   164
hep-cpp                  164
hep-go                   164
hep-rust                 164
xstest-should-refuse     154
donotanswer              136
llmbar-adver-neighbor    134
refusals-dangerous       100
llmbar-natural           100
alpacaeval-easy          100
refusals-offensive       100
alpacaeval-hard           95
alpacaeval-length         95
llmbar-adver-GPTInst      92
llmbar-adver-GPTOut       47
llmbar-adver-manual       46
mt-bench-med              40
mt-bench-hard             37
mt-bench-easy             28
Name: count, dtype: int64

In [6]:
# Model checkpoint path: model fine-tuned using DPO
CHECKPOINT_PATH = output_dir + '/checkpoint-20000'


# Device configuration
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {DEVICE}")

# Evaluation settings
BATCH_SIZE = 1
MAX_LENGTH = 512
SUBSET = "chat"  # Options: 'chat', 'chat_hard', 'safety', 'reasoning'
BETA = 0.1  # DPO temperature parameter (typically 0.1)

# Use reference model for implicit reward calculation?
USE_REFERENCE_MODEL = False
# USE_REFERENCE_MODEL = True

print(f"Checkpoint: {CHECKPOINT_PATH}")
print(f"RewardBench subset: {SUBSET}")
print(f"Beta (DPO temperature): {BETA}")

Using device: cuda
Checkpoint: /content/drive/Othercomputers/My Mac/Google Drive/Colab Notebooks/Reinforcement-learning/outputs/Gpt2-Reward/checkpoint-20000
RewardBench subset: chat
Beta (DPO temperature): 0.1

In [14]:
from dataclasses import dataclass

script_args = ScriptArguments(
    dataset_name="Anthropic/hh-rlhf"
)
training_args = RewardConfig(
    output_dir=output_dir,
    per_device_train_batch_size=5, # 10hrs for 10, 12 for 30+, 11.5 for 20, 8hrs for 5 on L4 GPU
    num_train_epochs=3,
    gradient_checkpointing=True,
    learning_rate=1e-5,
    eval_strategy="steps",
    save_total_limit=1,           # keeps only the best and the last checkpoint
    load_best_model_at_end=True,  # reloads the best model at the end of training
    metric_for_best_model="eval_loss", # monitor validation loss
    greater_is_better=False,      # lower loss is better
    eval_steps=10000,
    save_steps=10000,
    max_length=1024,
)
# training_args = TrainingArguments(
#     output_dir="./reward_model_checkpoints",
#     evaluation_strategy="epoch",  # or "steps"
#     save_strategy="epoch",        # must match evaluation_strategy
#     save_total_limit=1,           # keeps only the best and the last checkpoint
#     load_best_model_at_end=True,  # reloads the best model at the end of training
#     metric_for_best_model="eval_loss", # monitor validation loss
#     greater_is_better=False,      # lower loss is better
#     # other standard training args like learning_rate, batch_size, etc.
# )

model_args = ModelConfig(
    model_name_or_path=CHECKPOINT_PATH,
    # trust_remote_code=True,
)
training_args.gradient_checkpointing_kwargs = dict(use_reentrant=False)
dtype = model_args.dtype if model_args.dtype in ["auto", None] else getattr(torch, model_args.dtype)
model_kwargs = dict(
    revision=model_args.model_revision,
    use_cache=False if training_args.gradient_checkpointing else True,
    dtype=dtype,
)

quantization_config = get_quantization_config(model_args)
if quantization_config is not None:
    model_kwargs["device_map"] = get_kbit_device_map()
    model_kwargs["quantization_config"] = quantization_config

In [15]:
# Load model
from transformers import AutoTokenizer, AutoModelForCausalLM
print(f"Loading DPO model from: {CHECKPOINT_PATH}")

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(CHECKPOINT_PATH)

# Ensure pad token is set (required for GPT-2 based models)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
    print("Set pad_token to eos_token")

# Load reward model
model = AutoModelForSequenceClassification.from_pretrained(
    model_args.model_name_or_path,
    num_labels=1,
    trust_remote_code=model_args.trust_remote_code,
    **model_kwargs,
)
# model = AutoModelForCausalLM.from_pretrained(
#     CHECKPOINT_PATH,
#     torch_dtype=torch.float16 if DEVICE == "cuda" else torch.float32,
# )
REFERENCE_MODEL_PATH = 'gpt2'
if REFERENCE_MODEL_PATH == 'gpt2':
  gpt2_chat_template = r"""\
  {%- set sep = '\n\n' -%}
  {%- for m in messages -%}
  {%- if m['role'] == 'human' -%}
  Human: {{ m['content'] | trim }}{{ sep }}
  {%- elif m['role'] == 'assistant' -%}
  Assistant: {{ m['content'] | trim }}{{ sep }}
  {%- endif -%}
  {%- endfor -%}
  """
  # Attach at runtime:
  tokenizer.chat_template = gpt2_chat_template
model.to(DEVICE)
model.eval()

# Set pad token id in model config
if model.config.pad_token_id is None:
    model.config.pad_token_id = tokenizer.pad_token_id

print(f"✓ DPO model loaded successfully on {DEVICE}")
print(f"Model type: {model.config.model_type}")
print(f"Total parameters: {sum(p.numel() for p in model.parameters()):,}")

Loading DPO model from: /content/drive/Othercomputers/My Mac/Google Drive/Colab Notebooks/Reinforcement-learning/outputs/Gpt2-Reward/checkpoint-20000

Loading weights:   0%|          | 0/149 [00:00<?, ?it/s]

✓ DPO model loaded successfully on cuda
Model type: gpt2
Total parameters: 124,440,576

In [23]:
def get_log_prob(model, prompt, response):
    """
    Calculate the log probability of a response given a prompt.
    This is the key metric for evaluating DPO models.
    """
    # Combine prompt and response
    full_text = prompt + response

    # Tokenize
    inputs = tokenizer(
        full_text,
        return_tensors="pt",
        truncation=True,
        max_length=MAX_LENGTH
    ).to(DEVICE)

    # Also tokenize just the prompt to know where response starts
    prompt_inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=MAX_LENGTH
    ).to(DEVICE)

    prompt_length = prompt_inputs["input_ids"].shape[1]

    # Get logits
    with torch.no_grad():
        outputs = model(**inputs)
        # print(outputs)
        logits = outputs.logits

    # Get log probabilities for the response tokens only
    # Shift logits and labels for next-token prediction
    shift_logits = logits[:, prompt_length-1:-1, :]
    shift_labels = inputs["input_ids"][:, prompt_length:]

    # Calculate log probabilities
    log_probs = torch.nn.functional.log_softmax(shift_logits, dim=-1)

    # Gather log probs for actual tokens
    token_log_probs = torch.gather(
        log_probs,
        2,
        shift_labels.unsqueeze(-1)
    ).squeeze(-1)

    # Sum log probs (or mean for normalized score)
    total_log_prob = token_log_probs.sum().item()
    mean_log_prob = token_log_probs.mean().item()

    return {
        "total_log_prob": total_log_prob,
        "mean_log_prob": mean_log_prob,
        "num_tokens": shift_labels.shape[1]
    }


def get_reward_score(model, prompt, chosen, rejected):
    """
    Calculate DPO preference score between chosen and rejected responses.
    Returns the difference in rewards (should be positive if model prefers chosen).
    """
    inputs = tokenizer(prompt+chosen, return_tensors="pt").to(model.device)

    with torch.no_grad():
        reward_chosen = model(**inputs).logits.item()
    inputs = tokenizer(prompt+rejected, return_tensors="pt").to(model.device)

    with torch.no_grad():
        reward_rejected = model(**inputs).logits.item()


    return {
        "reward_chosen": reward_chosen,
        "reward_rejected": reward_rejected,
        "margin": reward_chosen - reward_rejected,
        "correct": reward_chosen > reward_rejected
    }

# Test the functions
print("\nTesting DPO scoring functions...")
test_prompt = "What is the capital of France?"
test_chosen = "The capital of France is Paris."
test_rejected = "The capital of France is Istanbul."
test_result = get_reward_score(model, test_prompt, test_chosen, test_rejected)
print(f"Test chosen reward: {test_result['reward_chosen']:.4f}")
print(f"Test rejected reward: {test_result['reward_rejected']}")

Testing DPO scoring functions...
Test chosen reward: 3.7529
Test rejected reward: 3.940537214279175

In [24]:
from tqdm import tqdm
import pandas as pd
results_df = None
# SUBSET = "alpacaeval-easy"  # Options: 'chat', 'chat_hard', 'safety', 'reasoning'
# SUBSET = "refusals-offensive"
SUBSET = "refusals-dangerous"
try:
    # Try importing RewardBench package
    try:
        from rewardbench import RewardBench
        print(f"Initializing RewardBench with subset: '{SUBSET}'")

        # Initialize RewardBench
        bench = RewardBench(
            subset=SUBSET,
            batch_size=BATCH_SIZE,
        )
        use_rewardbench_package = True

    except (ImportError, Exception) as e:
        # Fallback: Load from HuggingFace datasets
        print(f"RewardBench package not available: {e}")
        print("Loading RewardBench from HuggingFace datasets...")

        from datasets import load_dataset

        # Load the dataset
        dataset = load_dataset("allenai/reward-bench")

        # Use filtered split
        if "filtered" in dataset:
            bench = dataset["filtered"]
        else:
            bench = dataset["train"]

        print(f"Loaded {len(bench)} total examples")
        print(f"Available columns: {bench.column_names}")

        # Check unique subsets
        unique_subsets = bench.unique("subset")
        print(f"\nAvailable subsets: {unique_subsets}")

        # Filter by subset if specified and not "all"
        if SUBSET and SUBSET.lower() not in ["all", ""]:
            print(f"\nAttempting to filter for subset: '{SUBSET}'")

            # Try exact match first
            filtered = bench.filter(lambda x: x["subset"] == SUBSET)

            # If no results, try case-insensitive match
            if len(filtered) == 0:
                print(f"No exact matches. Trying case-insensitive match...")
                filtered = bench.filter(lambda x: x["subset"].lower() == SUBSET.lower())

            # If still no results, try partial match
            if len(filtered) == 0:
                print(f"No case-insensitive matches. Trying partial match...")
                filtered = bench.filter(lambda x: SUBSET.lower() in x["subset"].lower())

            # If still no results, show error but don't filter
            if len(filtered) == 0:
                print(f"⚠️  Warning: No matches found for subset '{SUBSET}'")
                print(f"Available subsets are: {unique_subsets}")
                print(f"Using ALL examples instead (first 100)")
                bench = bench.select(range(min(100, len(bench))))
            else:
                bench = filtered
                print(f"After filtering: {len(bench)} examples")
        else:
            # Use all data, but limit to reasonable number
            print(f"Using all subsets (limiting to 100 examples for speed)")
            bench = bench.select(range(min(100, len(bench))))

        use_rewardbench_package = False

    # Check if we have any data
    if len(bench) == 0:
        raise ValueError(f"No examples available after filtering!")

    print(f"\n{'='*80}")
    print(f"Evaluating {len(bench)} examples from RewardBench")
    print(f"{'='*80}\n")

    results = []

    # Evaluate with progress bar
    for idx, example in enumerate(tqdm(bench, desc="Evaluating")):
        try:
            # Handle different data formats
            if use_rewardbench_package:
                prompt = example["prompt"]
                chosen = example["chosen"]
                rejected = example["rejected"]
                category = example.get("category", "N/A")
            else:
                # HuggingFace dataset format
                prompt = example.get("prompt", "")
                chosen = example.get("chosen", "")
                rejected = example.get("rejected", "")
                category = example.get("subset", "N/A")

            # Skip if any field is empty
            if not prompt or not chosen or not rejected:
                continue

            # Get DPO preference scores
            result = get_reward_score(model, prompt, chosen, rejected)

            # Verify result structure
            if not isinstance(result, dict):
                continue

            results.append({
                "example_id": idx,
                "category": category,
                "reward_chosen": result.get("reward_chosen", 0.0),
                "reward_rejected": result.get("reward_rejected", 0.0),
                "margin": result.get("margin", 0.0),
                "correct": result.get("correct", False)
            })

            # Debug: print first result
            if idx == 0:
                print(f"First example subset: {category}")
                print(f"First result: {result}\n")

        except Exception as e:
            print(f"Error processing example {idx}: {e}")
            continue

    # Check if we got any results
    if not results:
        raise ValueError("No results were collected. Check get_dpo_preference_score() function.")

    results_df = pd.DataFrame(results)

    print(f"\n✓ DataFrame created with {len(results_df)} rows")

    print("\n" + "="*80)
    print("REWARDBENCH EVALUATION RESULTS (DPO MODEL)")
    print("="*80)

    # Overall metrics
    accuracy = results_df["correct"].mean() * 100
    avg_margin = results_df["margin"].mean()
    std_margin = results_df["margin"].std()

    print(f"\n📊 Overall Metrics:")
    print(f"  Accuracy: {accuracy:.2f}%")
    print(f"  Average Margin: {avg_margin:.4f}")
    print(f"  Std Dev Margin: {std_margin:.4f}")
    print(f"  Total Examples: {len(results_df)}")
    print(f"  Correct: {results_df['correct'].sum()}")
    print(f"  Incorrect: {(~results_df['correct']).sum()}")

    # Per-category breakdown
    if "category" in results_df.columns and results_df["category"].nunique() > 1:
        print("\n📂 Per-Category Performance:")
        category_stats = results_df.groupby("category").agg({
            "correct": ["mean", "count"],
            "margin": ["mean", "std"]
        }).round(4)

        category_stats.columns = ["Accuracy", "Count", "Avg Margin", "Std Margin"]
        category_stats["Accuracy"] = (category_stats["Accuracy"] * 100).round(2)

        display(category_stats.sort_values("Accuracy", ascending=False))

    # Quartile analysis
    print("\n📈 Margin Distribution (Quartiles):")
    quartiles = results_df["margin"].quantile([0.25, 0.5, 0.75])
    print(f"  25th percentile: {quartiles[0.25]:.4f}")
    print(f"  50th percentile (median): {quartiles[0.5]:.4f}")
    print(f"  75th percentile: {quartiles[0.75]:.4f}")

except Exception as e:
    print(f"⚠️  Error during RewardBench evaluation: {e}")
    print("Continuing with simple evaluation only...")
    import traceback
    traceback.print_exc()

RewardBench package not available: No module named 'rewardbench'
Loading RewardBench from HuggingFace datasets...
Loaded 2985 total examples
Available columns: ['prompt', 'chosen', 'chosen_model', 'rejected', 'rejected_model', 'subset', 'id']

Available subsets: ['alpacaeval-easy', 'alpacaeval-hard', 'alpacaeval-length', 'mt-bench-easy', 'mt-bench-med', 'mt-bench-hard', 'llmbar-natural', 'llmbar-adver-neighbor', 'llmbar-adver-GPTInst', 'llmbar-adver-GPTOut', 'llmbar-adver-manual', 'refusals-dangerous', 'refusals-offensive', 'xstest-should-respond', 'xstest-should-refuse', 'donotanswer', 'hep-python', 'hep-go', 'hep-cpp', 'hep-js', 'hep-rust', 'hep-java', 'math-prm']

Attempting to filter for subset: 'refusals-dangerous'

Filter:   0%|          | 0/2985 [00:00<?, ? examples/s]

After filtering: 100 examples

================================================================================
Evaluating 100 examples from RewardBench
================================================================================

Evaluating:   4%|▍         | 4/100 [00:00<00:02, 33.90it/s]

First example subset: refusals-dangerous
First result: {'reward_chosen': -0.5756182074546814, 'reward_rejected': 1.4010030031204224, 'margin': -1.9766212105751038, 'correct': False}

Evaluating: 100%|██████████| 100/100 [00:02<00:00, 44.21it/s]

✓ DataFrame created with 100 rows

================================================================================
REWARDBENCH EVALUATION RESULTS (DPO MODEL)
================================================================================

📊 Overall Metrics:
  Accuracy: 39.00%
  Average Margin: 0.0404
  Std Dev Margin: 4.6079
  Total Examples: 100
  Correct: 39
  Incorrect: 61

📈 Margin Distribution (Quartiles):
  25th percentile: -3.7855
  50th percentile (median): -2.0279
  75th percentile: 4.1678